<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

/**
 * VehiclesSeeder
 *
 * Seeds the full TASU university vehicle fleet (17 vehicles).
 * Data is sourced from the frontend's mock store and matches the
 * schema_mysql_3nf.sql seed data exactly.
 *
 * All vehicles are assigned to unit_id = 4 (TASU) and start with
 * status = 'available'.
 *
 * Run via: php spark db:seed VehiclesSeeder
 */
class VehiclesSeeder extends Seeder
{
    public function run(): void
    {
        $vehicles = [
            [
                'id'               => 1,
                'unit_id'          => 4,
                'plate_no'         => 'SFS 625',
                'model_name'       => 'Mitsubishi L300 Van',
                'model_year'       => '2004',
                'fuel_type'        => 'Diesel',
                'engine_specs'     => '2500 cc',
                'category'         => 'Van',
                'status'           => 'available',
                'registered_owner' => 'Benguet State University',
                'image_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Mitsubishi_L300_2.5_Diesel_2010.jpg/800px-Mitsubishi_L300_2.5_Diesel_2010.jpg',
            ],
            [
                'id'               => 2,
                'unit_id'          => 4,
                'plate_no'         => 'SAC 2710',
                'model_name'       => 'Toyota Hilux 4X4 E',
                'model_year'       => '2019',
                'fuel_type'        => 'Diesel',
                'engine_specs'     => '2393 cc',
                'category'         => 'Pickup',
                'status'           => 'available',
                'registered_owner' => 'Benguet State University',
                'image_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/2019_Toyota_Hilux_Invincible_D-4d_4WD_2.4_Front.jpg/800px-2019_Toyota_Hilux_Invincible_D-4d_4WD_2.4_Front.jpg',
            ],
            [
                'id'               => 3,
                'unit_id'          => 4,
                'plate_no'         => 'SAB 5997',
                'model_name'       => 'Yutong Bus',
                'model_year'       => '2017',
                'fuel_type'        => 'Diesel',
                'engine_specs'     => 'Euro 3',
                'category'         => 'Bus',
                'status'           => 'available',
                'registered_owner' => 'Benguet State University',
                'image_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Yutong_ZK6122H9_coach_in_Changchun.jpg/800px-Yutong_ZK6122H9_coach_in_Changchun.jpg',
            ],
            [
                'id'               => 4,
                'unit_id'          => 4,
                'plate_no'         => 'SAB 5998',
                'model_name'       => 'Yutong Coaster',
                'model_year'       => '2017',
                'fuel_type'        => 'Diesel',
                'engine_specs'     => 'Euro 3',
                'category'         => 'Bus',
                'status'           => 'available',
                'registered_owner' => 'Benguet State University',
                'image_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Yutong_ZK6729DG_in_Guangzhou.jpg/800px-Yutong_ZK6729DG_in_Guangzhou.jpg',
            ],
            [
                'id'               => 5,
                'unit_id'          => 4,
                'plate_no'         => 'CS: B7 H784',
                'model_name'       => 'Mitsubishi L300 FB',
                'model_year'       => '2020',
                'fuel_type'        => 'Diesel',
                'engine_specs'     => '2268 cc',
                'category'         => 'Van',
                'status'           => 'available',
                'registered_owner' => 'Benguet State University',
                'image_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Mitsubishi_L300_2.5_Diesel_2010.jpg/800px-Mitsubishi_L300_2.5_Diesel_2010.jpg',
            ],
            [
                'id'               => 6,
                'unit_id'          => 4,
                'plate_no'         => 'SFS 814',
                'model_name'       => 'Mitsubishi L-300 Van',
                'model_year'       => '2004',
                'fuel_type'        => 'Diesel',
                'engine_specs'     => '2400 cc',
                'category'         => 'Van',
                'status'           => 'available',
                'registered_owner' => 'Benguet State University',
                'image_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Mitsubishi_L300_2.5_Diesel_2010.jpg/800px-Mitsubishi_L300_2.5_Diesel_2010.jpg',
            ],
            [
                'id'               => 7,
                'unit_id'          => 4,
                'plate_no'         => 'SKA 939',
                'model_name'       => 'Nissan Urvan Estate',
                'model_year'       => '2011',
                'fuel_type'        => 'Diesel',
                'engine_specs'     => '2953 cc',
                'category'         => 'Van',
                'status'           => 'available',
                'registered_owner' => 'Benguet State University',
                'image_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/2012_Nissan_NV350_Urvan.jpg/800px-2012_Nissan_NV350_Urvan.jpg',
            ],
            [
                'id'               => 8,
                'unit_id'          => 4,
                'plate_no'         => 'SYA 2337',
                'model_name'       => 'Toyota Mini Bus',
                'model_year'       => '2020',
                'fuel_type'        => 'Diesel',
                'engine_specs'     => '4009 cc',
                'category'         => 'Bus',
                'status'           => 'available',
                'registered_owner' => 'Benguet State University',
                'image_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/2017_Toyota_Coaster.jpg/800px-2017_Toyota_Coaster.jpg',
            ],
            [
                'id'               => 9,
                'unit_id'          => 4,
                'plate_no'         => 'SDN 570',
                'model_name'       => 'SUV Land Cruiser',
                'model_year'       => '1992',
                'fuel_type'        => 'Diesel',
                'engine_specs'     => '4164 cc',
                'category'         => 'SUV',
                'status'           => 'available',
                'registered_owner' => 'Benguet State University',
                'image_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/2021_Toyota_Land_Cruiser_LC300_3.5_ZX_%28VJA300W%29.jpg/800px-2021_Toyota_Land_Cruiser_LC300_3.5_ZX_%28VJA300W%29.jpg',
            ],
            [
                'id'               => 10,
                'unit_id'          => 4,
                'plate_no'         => 'SYA 2338',
                'model_name'       => 'Toyota HiAce GL',
                'model_year'       => '2021',
                'fuel_type'        => 'Diesel',
                'engine_specs'     => '2755 cc',
                'category'         => 'Van',
                'status'           => 'available',
                'registered_owner' => 'Benguet State University',
                'image_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/2019_Toyota_HiAce_GL_Grandia_Tourer.jpg/800px-2019_Toyota_HiAce_GL_Grandia_Tourer.jpg',
            ],
            [
                'id'               => 11,
                'unit_id'          => 4,
                'plate_no'         => 'SAC 1399',
                'model_name'       => 'Toyota HiAce Commuter',
                'model_year'       => '2024',
                'fuel_type'        => 'Diesel',
                'engine_specs'     => '3000 cc',
                'category'         => 'Van',
                'status'           => 'available',
                'registered_owner' => 'Benguet State University',
                'image_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/2019_Toyota_HiAce_Commuter_Deluxe.jpg/800px-2019_Toyota_HiAce_Commuter_Deluxe.jpg',
            ],
            [
                'id'               => 12,
                'unit_id'          => 4,
                'plate_no'         => 'SYA 1097',
                'model_name'       => 'Toyota HiAce Tourer (A)',
                'model_year'       => '2025',
                'fuel_type'        => 'Diesel',
                'engine_specs'     => '2.8L',
                'category'         => 'Van',
                'status'           => 'available',
                'registered_owner' => 'Benguet State University',
                'image_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/2019_Toyota_HiAce_GL_Grandia_Tourer_2.8.jpg/800px-2019_Toyota_HiAce_GL_Grandia_Tourer_2.8.jpg',
            ],
            [
                'id'               => 13,
                'unit_id'          => 4,
                'plate_no'         => 'SYA 1098',
                'model_name'       => 'Toyota HiAce Tourer (B)',
                'model_year'       => '2025',
                'fuel_type'        => 'Diesel',
                'engine_specs'     => '2.8L',
                'category'         => 'Van',
                'status'           => 'available',
                'registered_owner' => 'Benguet State University',
                'image_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/2019_Toyota_HiAce_GL_Grandia_Tourer_2.8.jpg/800px-2019_Toyota_HiAce_GL_Grandia_Tourer_2.8.jpg',
            ],
            [
                'id'               => 14,
                'unit_id'          => 4,
                'plate_no'         => 'SYA 1099',
                'model_name'       => 'Toyota HiAce Tourer (C)',
                'model_year'       => '2025',
                'fuel_type'        => 'Diesel',
                'engine_specs'     => '2.8L',
                'category'         => 'Van',
                'status'           => 'available',
                'registered_owner' => 'Benguet State University',
                'image_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/2019_Toyota_HiAce_GL_Grandia_Tourer_2.8.jpg/800px-2019_Toyota_HiAce_GL_Grandia_Tourer_2.8.jpg',
            ],
            [
                'id'               => 15,
                'unit_id'          => 4,
                'plate_no'         => 'JM 2748',
                'model_name'       => 'HINO Refrigerated Van (A)',
                'model_year'       => '2017',
                'fuel_type'        => 'Diesel',
                'engine_specs'     => '4500 cc',
                'category'         => 'Logistics',
                'status'           => 'available',
                'registered_owner' => 'Benguet State University',
                'image_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Hino_Dutro_12.jpg/800px-Hino_Dutro_12.jpg',
            ],
            [
                'id'               => 16,
                'unit_id'          => 4,
                'plate_no'         => 'SAC 1400',
                'model_name'       => 'Toyota LiteAce Pick Up',
                'model_year'       => '2024',
                'fuel_type'        => 'Gasoline',
                'engine_specs'     => '1.5L',
                'category'         => 'Pickup',
                'status'           => 'available',
                'registered_owner' => 'Benguet State University',
                'image_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Toyota_LiteAce_pickup_%281%29.jpg/800px-Toyota_LiteAce_pickup_%281%29.jpg',
            ],
            [
                'id'               => 17,
                'unit_id'          => 4,
                'plate_no'         => 'JM 2503',
                'model_name'       => 'HINO Refrigerated Van (B)',
                'model_year'       => '2017',
                'fuel_type'        => 'Diesel',
                'engine_specs'     => '4500 cc',
                'category'         => 'Logistics',
                'status'           => 'available',
                'registered_owner' => 'Benguet State University',
                'image_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Hino_Dutro_12.jpg/800px-Hino_Dutro_12.jpg',
            ],
        ];

        $this->db->table('vehicles')->ignore(true)->insertBatch($vehicles);
    }
}
